### ISSUE TITLE
Implement shortlist of components

### ISSUE THREAD

**Issue by zenorocha** [liferay-apps/styleguide#3]
- [x] Avatar
    - [x] Photo
    - [x] Initials
    - [x] Icon
- [x] Button
    - [x] Primary
    - [x] Disabled
- [x]  Form
    - [x] Input
    - [x] Select
    - [x] Textarea
- [x] Tooltip
- [x] Tooltip · Menu
- [x] Modal
- [x] Nav · Main
- [x] Nav · Aux
- [x] Shadow

**Comment by vitorfernandes** [comment]
- [ ] Test
